### ISSUE TITLE
`opt/chocolatey/lib`

### ISSUE THREAD

**Issue by smusali** [Linuturk/mono-choco#11]
Hi.

Whenever I try `choco pack` or `choco --allow-unofficial pack` or `mono /opt/chocolatey/choco.exe "$@" --allow-unofficial pack`, etc., it fails and says: 
```
Chocolatey v0.10.9.0
Directory 'opt/chocolatey/lib' does not exist.
```

In using `choco`, I think `choco pack` and `choco push` are the main commands and if they are not working, there is no huge encouraging point in using this docker image, honestly.

By the way, just for better analysis, inside the `mono-choco` container:
- `mono --version`:
```
Mono JIT compiler version 4.6.2 (Debian 4.6.2.7+dfsg-1)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
	TLS:           __thread
	SIGSEGV:       altstack
	Notifications: epoll
	Architecture:  amd64
	Disabled:      none
	Misc:          softdebug 
	LLVM:          supported, not enabled.
	GC:            sgen
```
- `choco --version`:
```
0.10.9.0
```
- `which choco`:
```
/usr/bin/choco
```

So, can you tell me what I am doing wrong here?

Thanks in advance!

And thanks for easing the process for us to be able to use `choco` on `linux`!

**Comment by Linuturk** [comment]
Sorry for the late response. Was on holiday. Were you able to solve the issue you were seeing?

**Comment by smusali** [comment]
@Linuturk, don't worry - it was working despite of outputing error message at the same time - I solved by just redirecting the error into `/dev/null`
