### ISSUE TITLE
Document workaround for "Cannot create a package that has no dependencies nor content."

### ISSUE THREAD

**Issue by rfay** [Linuturk/mono-choco#12]
Using `docker run --rm -v $PWD:$PWD -w $PWD linuturk/mono-choco pack ddev.nuspec` I got just "Cannot create a package that has no dependencies nor content."

However, if I just do a `choco pack ddev.nuspec` with the exact same file mounted into Windows, I get a successful pack. 

The answer seems to be a comment buried at the bottom of the generated nuspec file:
`<!--Building from Linux? You may need this instead: <file src="tools/**" target="tools" />-->`

I changed to that and then was able to do the pack operation.

I'll happily do a PR if you suggest where you'd like the info.

**Comment by Linuturk** [comment]
Hopefully that's what you had in mind.

**Comment by rfay** [comment]
Thanks! I would have put it more strongly. Like "Make sure you have

`<file src="tools/**" target="tools" />`

in the `<files>` stanza, as noted in the template:
`<!--Building from Linux? You may need this instead: <file src="tools/**" target="tools" />-->`

but all good! It's enough to give a hint now.

**Comment by Linuturk** [comment]
Feel free to PR :)
