### ISSUE TITLE
Push new tag (or update latest) on hub.docker.com?

### ISSUE THREAD

**Issue by rfay** [Linuturk/mono-choco#14]
Thanks for this project, it's a lifesaver for those of us whose infra is not on Windows, but have to support Windows.

I note that the last push on https://hub.docker.com/r/linuturk/mono-choco/tags is about a year ago, and am a little insecure about the version of choco in there. Could it be updated? It might be worthwhile to use explicit tags for the choco version?

Thanks!

**Comment by Linuturk** [comment]
When we updated this repo, it triggered a build automatically. I have an open issue with the upstream to get them to trigger their own builds from their repo, but it hasn't seen movement.

https://github.com/chocolatey/choco/pull/1153#issuecomment-297561789

Maybe I should open a separate issue to track that.

**Comment by rfay** [comment]
Not sure dockerhub builds will work out, but that would be fine. However, the current one is more than a year old; tagged pushes by version are probably better for user stability.

**Comment by Linuturk** [comment]
I'll have to start tracking the versions with upstream vs using the stable.zip. There's value there for sure, but I think it's better for upstream to setup their own image, honestly. I'll open an issue with them that we can track.

**Comment by Linuturk** [comment]
See the referenced upstream issue. Based on the response, we can explore a work around in this project or focus on upstream.

**Comment by Linuturk** [comment]
Going to close this in favor of https://github.com/chocolatey/choco/issues/1718
