### ISSUE TITLE
Chocolatey needs to been updated

### ISSUE THREAD

**Issue by rekire** [Linuturk/mono-choco#18]
As reported in #17 you cannot push packages with your image. Please update your image when https://github.com/chocolatey/choco/pull/1827 is merged.

**Comment by Linuturk** [comment]
Will do.

**Comment by rfay** [comment]
https://github.com/chocolatey/choco/pull/1827 has been merged, yay! Would appreciate a new image push.

**Comment by Linuturk** [comment]
Please see the linked PR to see if it fixes your issue. The build was clean locally, but I want to make sure it works before I merge to master and publish a fresh image.
