### ISSUE TITLE
Turn Dockerfile into a multi-stage build

### ISSUE THREAD

**Issue by philippgille** [Linuturk/mono-choco#3]
The [current Dockerfile](https://github.com/Linuturk/mono-choco/blob/df83b13a03ea77b70e00d8339cf9a503ec6531a4/Dockerfile) uses many image layers and also *builds* the `choco` executable in the same image that gets later used for *running* `choco`.

Since [Docker 17.05.0-ce](https://docs.docker.com/release-notes/docker-ce/#17050-ce-2017-05-04) there are multi-stage builds, which enables building *two* (or more) Docker images within one Dockerfile, while only the last one will be used for distribution.

This is most useful for images where a static binary gets built (e.g. the first Docker image inherits from the 273 MB `golang`, building the static binary with Go, then the second Docker image inherits from the tiny `scratch` or 2 MB `alpine`, only adding the built binary from the previous image, making the image much smaller). But it's nice in other cases as well.

See [https://docs.docker.com/engine/userguide/eng-image/multistage-build/](https://docs.docker.com/engine/userguide/eng-image/multistage-build/).

Also, some `RUN` steps can be combined, leading to fewer image layers.

I'm willing to create a PR for that if you don't mind.

**Comment by Linuturk** [comment]
Thanks for the suggestion. Happy to review any PR you create.
