### ISSUE TITLE
Illustration?

### ISSUE THREAD

**Issue by petemounce** [Linuturk/mono-choco#5]
Hi there - thank you very much for creating this! It has saved me doing the same.

I've tried to use it, so far unsuccessfully.

You can see my attempt within bazelbuild/bazel#4559 - as far as I can tell, the nuspec is valid after I generate it via some variable expansion. However, the command to `pack` seems to just hang.

I'm also not quite comfortable yet with docker; I wasn't sure of the following

* how to mount the local directory as a read/write volume - I had a problem with `--volume` and so instead used `--mount`.
* whether I'm right to expect the `nupkg` to be generated into the directory that I mount

Would it be possible to add a worked example to the readme? If you wanted to use the code in my bash PR linked, please be welcome.

**Comment by Linuturk** [comment]
Checkout the example directory I've added. Hopefully that makes things more clear.
